[package]
name = "raspicam"
version = "0.1.0"
authors = ["pawanbisht62 <pawanbisht62@gmail.com>"]
license = "Apache-2.0"
description = "Tiny Rust library for playing with RaspberryPi's camera."
repository = "https://github.com/pawanbisht62/raspicam"
edition = "2018"

[dependencies]